import Head from 'next/head'
import { HomePage } from "@/components/home/HomePage"

export default function Home({title, data}) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <HomePage data={data} />
    </>
  )
}

export async function getServerSideProps() {
  const { events_categories } = await import('../../data/data.json');
  return {
    props: {
      title: "Hello Everyone",
      data: events_categories,
    },
  };
}
